version: 'latest'

services:
  nancy:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - nancy_data:/var/lib/postgresql/data

  auth:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: supertokens_user 
      POSTGRES_PASSWORD: somePassword 
      POSTGRES_DB: supertokens
    ports:
      - 5433:5433
    networks:
      - app_network
  
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:9.1.0
    restart: always
    depends_on:
      - auth
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://supertokens_user:somePassword@db:5433/supertokens"
    networks:
      - app_network

volumes:
  nancy_data:

networks:
  app_network:
    driver: bridge
